// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Message struct {
	// The message text
	Text string `json:"text"`
}

func (m *Message) GetText() string {
	if m == nil {
		return ""
	}
	return m.Text
}
