// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package config

import (
	"github.com/speakeasy/terraform-provider-test/internal/sdk/retry"
	"net/http"
	"time"
)

type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

type SDKConfiguration struct {
	Client HTTPClient

	ServerURL         string
	ServerIndex       int
	ServerList        []string
	UserAgent         string
	SDKVersion        string
	GenVersion        string
	OpenAPIDocVersion string
	RetryConfig       *retry.Config
	Timeout           *time.Duration
}

func (c *SDKConfiguration) GetServerDetails() (string, map[string]string) {
	if c.ServerURL != "" {
		return c.ServerURL, nil
	}

	return c.ServerList[c.ServerIndex], nil
}
