workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Test API:
        inputs:
            - location: openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/lambda/ll/test-api
targets:
    test:
        target: terraform
        source: Test API
