// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-test/internal/sdk/models/shared"
)

func (r *MessageDataSourceModel) RefreshFromSharedMessage(ctx context.Context, resp *shared.Message) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Text = types.StringValue(resp.Text)
	}

	return diags
}
