// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/action"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/ephemeral"
	"github.com/hashicorp/terraform-plugin-framework/function"
	"github.com/hashicorp/terraform-plugin-framework/list"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-test/internal/sdk"
	"net/http"
)

var _ provider.Provider = (*TestProvider)(nil)
var _ provider.ProviderWithActions = (*TestProvider)(nil)
var _ provider.ProviderWithEphemeralResources = (*TestProvider)(nil)
var _ provider.ProviderWithFunctions = (*TestProvider)(nil)

type TestProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// TestProviderModel describes the provider data model.
type TestProviderModel struct {
	ServerURL types.String `tfsdk:"server_url"`
}

func (p *TestProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "test"
	resp.Version = p.version
}

func (p *TestProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"server_url": schema.StringAttribute{
				Description: `Server URL (defaults to https://api.example.com)`,
				Optional:    true,
			},
		},
	}
}

func (p *TestProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data TestProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	serverUrl := data.ServerURL.ValueString()

	if serverUrl == "" {
		serverUrl = "https://api.example.com"
	}

	providerHTTPTransportOpts := ProviderHTTPTransportOpts{
		SetHeaders: make(map[string]string),
		Transport:  http.DefaultTransport,
	}

	httpClient := http.DefaultClient
	httpClient.Transport = NewProviderHTTPTransport(providerHTTPTransportOpts)

	opts := []sdk.SDKOption{
		sdk.WithServerURL(serverUrl),
		sdk.WithClient(httpClient),
	}

	client := sdk.New(opts...)
	resp.ActionData = client
	resp.DataSourceData = client
	resp.EphemeralResourceData = client
	resp.ListResourceData = client
	resp.ResourceData = client
}

func (p *TestProvider) Functions(_ context.Context) []func() function.Function {
	return []func() function.Function{}
}

func (p *TestProvider) Actions(_ context.Context) []func() action.Action {
	return []func() action.Action{}
}

func (p *TestProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{}
}

func (p *TestProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewMessageDataSource,
	}
}

func (p *TestProvider) EphemeralResources(ctx context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{}
}

func (p *TestProvider) ListResources(ctx context.Context) []func() list.ListResource {
	return []func() list.ListResource{}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &TestProvider{
			version: version,
		}
	}
}
